# the state of develop branch after PR 29 (AXA-1636) has been merged
set ( ASKAP_CMAKE_TAG              30a2e560c549865aeb4743df1ae6f793c5ef656d CACHE  STRING    "askap.cmake tools"                FORCE )
set ( LOFAR_COMMON_TAG             tags/1.2.0                               CACHE  STRING    "lofar-common version"             FORCE )
set ( LOFAR_BLOB_TAG               tags/1.2.0                               CACHE  STRING    "lofar-blob version"               FORCE )
# the state of develop branch after PR 38 (version work)
set ( BASE_ASKAP_TAG               dbd45d57cd9829f334004227383b9654dec3ac45 CACHE  STRING    "base-askap version"               FORCE )
set ( BASE_ASKAPPARRALLEL_TAG      tags/1.2.0                               CACHE  STRING    "base-askapparrallel version"      FORCE )
set ( BASE_IMAGEMATH_TAG           tags/1.4.0                               CACHE  STRING    "base-imagemath version"           FORCE )
# the state of develop branch after PR 52 (AXA-689 changes compatible with the old casacore, hence merged)
set ( BASE_SCIMATH_TAG             359a814402b8d70ab70b3387c26eba89fa86be87 CACHE  STRING    "base-scimath version"             FORCE )
