set ( ASKAP_CMAKE_TAG              tags/1.3.0                               CACHE  STRING    "askap.cmake tools"                FORCE )
set ( LOFAR_COMMON_TAG             tags/1.2.0                               CACHE  STRING    "lofar-common version"             FORCE )
set ( LOFAR_BLOB_TAG               tags/1.3.0                               CACHE  STRING    "lofar-blob version"               FORCE )
set ( BASE_ASKAP_TAG               tags/1.5.0                               CACHE  STRING    "base-askap version"               FORCE )
set ( BASE_ASKAPPARRALLEL_TAG      tags/1.3.1                               CACHE  STRING    "base-askapparrallel version"      FORCE )
set ( BASE_IMAGEMATH_TAG           tags/1.6.1                               CACHE  STRING    "base-imagemath version"           FORCE )
set ( BASE_SCIMATH_TAG             tags/1.7.1                               CACHE  STRING    "base-scimath version"             FORCE )
